### ISSUE TITLE
Use of jump, longjump

### ISSUE THREAD

**Issue by thk686** [Reputeless/Xoshiro-cpp#1]
I'd like to use this with mpi where each process has a different stream. Since jump/longjump do not have any parameters, how does one use them? Does one call jump/longjump rank times? Thanks.

**Comment by Reputeless** [comment]
`jump()` and `longJump()` in this library is the same as David Blackman and Sebastiano Vigna's original implementation which do not have any parameters.
Here is my example code of jumping.
```cpp
constexpr std::uint64_t MySeed = 12345;
XoshiroCpp::Xoroshiro128PlusPlus g_rng{ MySeed };
std::mutex g_mutex;

XoshiroCpp::Xoroshiro128PlusPlus MakeRNG()
{
	std::lock_guard lock{ g_mutex };
	auto t = g_rng;
	g_rng.jump();
	return t;
}

void Task()
{
	auto rng = MakeRNG();
}

int main()
{
	std::vector<std::future<void>> tasks;

	for (int i = 0; i < 100; ++i)
	{
		tasks.push_back(std::async(std::launch::async, Task));
	}
}
```
