### ISSUE TITLE
How to generate random numbers

### ISSUE THREAD

**Issue by romanholidaypancakes** [Reputeless/Xoshiro-cpp#4]
Which api can i use to generate random numbers, i use your example to generate the same value every time

**Comment by Reputeless** [comment]
As with all other [pseudo-random number generators](https://en.wikipedia.org/wiki/Pseudorandom_number_generator), if the seed value is the same, the generated random number sequence is always the same.

You can make a non-deterministic seed value by the following methods:

- Using [std::random_device](https://en.cppreference.com/w/cpp/numeric/random/random_device)

```cpp
# include <iostream>
# include <random> // std::random_device, std::uniform_int_distribution
# include "XoshiroCpp.hpp"

int main()
{
    std::random_device rd;
    std::uniform_int_distribution<std::uint64_t> dist{ 0ULL, std::numeric_limits<std::uint64_t>::max() };
    const std::uint64_t seed = dist(rd);
    std::cout << "seed: " << seed << '\n';

    using namespace XoshiroCpp;
    Xoshiro256PlusPlus rng(seed);

    for (int i = 0; i < 5; ++i)
    {
        std::cout << rng() << '\n';
    }
}
```

- Using time
- Using a seed value entered by the user

**Comment by romanholidaypancakes** [comment]
I have a question, in fact the following code can generate a random value
````
     std::random_device rd;
     std::uniform_int_distribution<std::uint64_t> dist{ 0ULL, std::numeric_limits<std::uint64_t>::max() };
     const std::uint64_t seed = dist(rd);
````
So why do we need other pseudo-random algorithms, because no matter the `seed` value is the same, then all random algorithms generate the same value multiple times.

**Comment by Reputeless** [comment]
For runtime performance and reproducibility.
`std::random_device` is very slow.
